# Generated by Django 5.2.13 on 2026-04-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='새로운 모임', max_length=100),
        ),
    ]
